######################################################
# Configure the options in this file to your liking.
# https://github.com/mojombo/jekyll/wiki/configuration
######################################################

## Site author's information.
author:
  ## Author's name, <meta name=author> in _layouts/default.html and used in
  ## humans.txt
  name:      Kaleb Hornsby
  ## Author's title
  title:     Software Engineer
  ## Author's email address
  email:     kaleb@hornsby.ws
  ## Author's web site
  url:       http://kaleb.hornsby.ws
  ## Author's location
  location:  "Augusta, GA, US"
  ## Author's github user name
  gh:
    user:    kaleb
    repo:    kaleb.github.com
  ## Author's twitter name
  twitter:   thekaleb
  disqus: 
    shortname: gh-pages-boilerplate

cat:
  comp:
    descr: Computer-Related Topics
    cat:
      databases:
        descr: Database and Data Management Issues and Theory
      editors:
        descr: Topics Related to Computerized Text Editing
      internet:
        descr: The International Computer Network
        cat:
          services:
            descr: Internet Services
            cat:
              google:
                descr: Search, Gmail, Groups, Maps, Picasa, etc.
              wiki:
                descr: Wikis, Such as Wikipedia
      lang:
        descr: Programing Languages
        cat:
          awk:
            descr: The AWK Programming Language
          c:
            descr: The C Programming Language
          c++:
            descr: The Object-Oriented C++ Programming Language
          csharp:
            descr: The C# Programming Language
          haskell:
            descr: 
          javascript:
            descr: ECMAScript and JavaScript Programming Languages
          go:
            descr: The Go Programming Language
          python:
            descr: The Python Computer Language 
      misc:
        descr: General Topics About Computers Not Covered Elsewhere
      org:
        descr: Computer Organizations and Clubs
      os:
        descr: Computer Operating Systems
        cat:
      programming:
        descr: Programming Issues That Transcend Languages and OSs
        cat:
          contests:
            descr: Announcements and Results of Programming Contests
      text:
        descr: 
        cat: 
  rec:
    descr: Recreational Activities
    cat:
  sci:
    descr: Scientific Subjects
    cat:
  soc:
    descr: Socialising and Social Issues
    cat:
  talk:
    descr: Contentious Issues

## The absolute URL of your site. Should be user.github.com or whatever is in
## the root CNAME file
url:         http://kaleb.hornsby.ws

## The name of the site, <title> and <h1> in _layouts/default.html
title:       Kaleb Hornsby

## <meta name=description> and <h2> in /_layouts/default.html
description: Software Developer in Augusta, GA

## <meta name=keywords> in  /_layouts/default.html, probably not useful anymore.
keywords:    [ HTML5, CSS3, JavaScript, ES5, Linux ]

## Splits your posts up over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate:    5

## Google Analytics id.
ga: XXXXX-X

## A list of directories and files to exclude from the conversion
exclude: [ ]

#################
# Jekyll Defaults
#################

## 
#future:      true

## Uses RDiscount or [engine] instead of Maruku. Maruku is the default.
markdown:    maruku

## Controls the URLs that posts are generated with.
## https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

## Enables or disables Jekyll from recreating the site when files are modified.
#auto:        false

## Fires up a server that will host your _site directory
#server:      false

## Changes the port that the Jekyll server will run on
#server_port: 4000

##
#plugins:     ./_plugins

## Maruku options, if it is being used.
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

## RDiscount options, if it is being used.
rdiscount:
  extensions: []

## Kramdown options, if it is being used.
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

########################
# Github Pages Overrides
########################

## Produces an index for related posts.
#lsi:         false

## Enables highlight tag with Pygments.
pygments:    yes

##
#safe:        false

## Changes the directory where Jekyll will look to transform files
#source:      .

## Changes the directory where Jekyll will write files to
#destination: ./_site
